-- seed_workflow_node_definitions.sql — 節點型別定義出廠 seed（安裝用）
-- 本檔由 scripts/export_node_definitions_seed.py 從 dev 庫自動產生，禁止手改。
-- 冪等：以 node_type 唯一鍵 ON CONFLICT DO NOTHING（既有定義不覆蓋）。
--
-- 執行必須帶 system_org 變數（系統企業 secure_code，即 .env 的 SYSTEM_ORG_CODE）：
--   psql -v system_org="$SYSTEM_ORG_CODE" -f scripts/sql/seed_workflow_node_definitions.sql

BEGIN;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('122cb0366ce22b1efc59e4', 'AiAgent', 'SYSTEM', :'system_org', '整合', 'AI 分析', '把流程資料交給本機 CLI 型 LLM 分析，結果寫入流程變數並可插入簽核註記', '/static/modules/form_workflow/icons/workflow/aiagent.svg', 'modules.form_workflow.services.node_handlers.ai_agent_handler.AiAgentHandler', '{"model": "string", "on_error": "string", "result_var": "string", "instruction": "string", "decode_payload": "boolean", "timeout_seconds": "integer", "payload_template": "string", "write_approval_note": "boolean"}'::jsonb, 'roundrectangle', '#3B82F6', 120, 60, -1, -1, 120, 3600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('97b069fe958654628e0f2e85057dc29d', 'AlertBroadcast', 'SYSTEM', NULL, '通知', '緊急廣播', '全頁強制彈窗，用戶必須確認已讀才能關閉', '/static/modules/form_workflow/icons/workflow/alertbroadcast.svg', 'modules.form_workflow.services.node_handlers.alert_broadcast_handler.AlertBroadcastHandler', '{"title": "string", "message": "string", "require_ack": "boolean", "target_type": "string", "target_roles": "array", "broadcast_code": "string", "target_departments": "array"}'::jsonb, 'roundrectangle', '#3B82F6', 120, 60, -1, -1, 120, 3600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('124207a0ad53e5c1c4b319591ca851a6', 'ApiKeyAction', 'SYSTEM', NULL, '安全', 'API Key 處置', '暫停或復原平台 API Key（機器處置疑似盜用）。可處置發動本流程的 Key、指定 Key，或由變數解析 key_id。暫停原因支援變數，如 ${fi.serial}。', '/static/modules/form_workflow/icons/workflow/apikeyaction.svg', 'modules.form_workflow.services.node_handlers.api_key_action_handler.ApiKeyActionHandler', '{"action": "string", "key_id": "string", "reason": "string", "key_source": "string"}'::jsonb, 'roundrectangle', '#DC2626', 140, 60, -1, -1, 60, 600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('5441efd70e0c22449a03a7222c09524c', 'ApiKeyIssue', 'SYSTEM', NULL, '安全', 'API Key 核發', '依核准後的申請單建立平台 API Key，並產生一次性領取憑證；secret 不寫入流程變數或節點結果。', '/static/modules/form_workflow/icons/workflow/apikeyaction.svg', 'modules.form_workflow.services.node_handlers.api_key_issue_handler.ApiKeyIssueHandler', '{"result_var": "string", "forms_field": "string", "expires_field": "string", "purpose_field": "string", "claim_ttl_hours": "integer", "allowed_ips_field": "string", "beneficiary_field": "string"}'::jsonb, 'roundrectangle', '#DC2626', 140, 60, -1, -1, 60, 600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('9kP6lgt3spT/jUv7eSg10A==', 'Branch', 'SYSTEM', NULL, '控制', '分支', '根據條件選擇路徑', '/static/modules/form_workflow/icons/workflow/branch.svg', 'modules.form_workflow.services.node_handlers.branch_handler.BranchHandler', '{}'::jsonb, 'diamond', '#F59E0B', 100, 100, 1, -1, 60, 3600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('85032bc60e05ed3e2514ca07509aa809', 'DecisionWriter', 'SYSTEM', NULL, '資安處置', '防禦決策', '寫入一筆 OpenDefense 防禦決策(廠牌中性);任何外部執行端依 enforcement_points 篩選後拉取執行。target_value 通常引用表單欄位,如 ${f.actor_ip}。', '/static/modules/form_workflow/icons/workflow/decisionwriter.svg', 'modules.form_workflow.services.node_handlers.decision_writer_handler.DecisionWriterHandler', '{"action": "string", "severity": "string", "decided_via": "string", "target_type": "string", "ttl_seconds": "integer", "on_protected": "string", "target_value": "string", "reason_template": "string", "enforcement_points": "array", "allow_protected_target": "boolean"}'::jsonb, 'roundrectangle', '#DC2626', 140, 60, -1, -1, 60, 600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('doEEwNjUAwjSwMSGj9lHJg==', 'Delay', 'SYSTEM', NULL, '控制', '暫停', '延遲執行指定時間', '/static/modules/form_workflow/icons/workflow/delay.svg', 'modules.form_workflow.services.node_handlers.delay_handler.DelayHandler', '{"delay_seconds": "number"}'::jsonb, 'roundrectangle', '#64748B', 120, 60, 1, 1, 86400, 3600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('I5ISFKq7gT81XsDD8hbCTAh9', 'EmailAdapter', 'SYSTEM', NULL, '通知', 'Email 通知', '發送 Email', '/static/modules/form_workflow/icons/workflow/emailadapter.svg', 'modules.form_workflow.services.node_handlers.email_handler.EmailHandler', '{"to": "string", "body": "string", "subject": "string"}'::jsonb, 'roundrectangle', '#3B82F6', 120, 60, -1, -1, 120, 3600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('xYPO6zCZY5eQTSiFIp/ybg==', 'End', 'SYSTEM', NULL, '基本', '結束', '流程的終點', '/static/modules/form_workflow/icons/workflow/end.svg', 'modules.form_workflow.services.node_handlers.end_handler.EndHandler', '{}'::jsonb, 'ellipse', '#EF4444', 80, 80, -1, 0, 30, 3600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('0u3uSpWyzvLlh3AT9llS9Q==', 'FormAdapter', 'SYSTEM', NULL, '表單', '簽核', '表單簽核節點', '/static/modules/form_workflow/icons/workflow/formadapter.svg', 'modules.form_workflow.services.node_handlers.formadapter_handler.FormAdapterHandler', '{"approvalMode": "string", "assigneeType": "string", "assigneeValue": "string"}'::jsonb, 'roundrectangle', '#0EA5E9', 140, 70, 1, 2, 172800, 3600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('5ec121dea68152632ba4e18adf1a6a61', 'NavbarBroadcast', 'SYSTEM', NULL, '通知', '跑馬燈廣播', '在 Navbar 顯示跑馬燈訊息，支援啟動/停止兩種模式', '/static/modules/form_workflow/icons/workflow/navbarbroadcast.svg', 'modules.form_workflow.services.node_handlers.navbar_broadcast_handler.NavbarBroadcastHandler', '{"mode": "string", "message": "string", "bg_color": "string", "text_color": "string", "broadcast_code": "string", "display_seconds": "number", "duration_minutes": "number"}'::jsonb, 'roundrectangle', '#3B82F6', 120, 60, -1, -1, 120, 3600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('KIqHBWG3OIDByQ8lAsdgoA==', 'OpFieldRead', 'SYSTEM', NULL, '變數', '讀取欄位', '從表單讀取欄位到變數', '/static/modules/form_workflow/icons/workflow/opfieldread.svg', 'modules.form_workflow.services.node_handlers.fieldread_handler.FieldReadHandler', '{"mappings": "array"}'::jsonb, 'roundrectangle', '#14B8A6', 120, 60, 1, 1, 60, 3600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('C9a+u2hHDyCYT7iwre+0WA==', 'OpFieldWrite', 'SYSTEM', NULL, '變數', '寫入欄位', '將變數寫入表單欄位', '/static/modules/form_workflow/icons/workflow/opfieldwrite.svg', 'modules.form_workflow.services.node_handlers.fieldwrite_handler.FieldWriteHandler', '{"mappings": "array"}'::jsonb, 'roundrectangle', '#06B6D4', 120, 60, 1, 1, 60, 3600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('33e07c052fb00d303aaf7fbfcdb5c730', 'OpHrLookup', 'SYSTEM', NULL, '變數', '人事資料取值', '讀取成員職級、職稱、職系、部門、直屬主管與核決上限並寫入流程變數。', '/static/modules/form_workflow/icons/workflow/ophrlookup.svg', 'modules.form_workflow.services.node_handlers.hr_lookup_handler.HrLookupHandler', '{"var_prefix": "string", "amount_expr": "string", "target_expr": "string", "approver_mode": "boolean", "target_source": "string", "approval_category_code": "string"}'::jsonb, 'roundrectangle', '#3B82F6', 120, 60, 1, 1, 60, 3600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('GtzjtXtTiJPnuhOGYrIKmA==', 'OpSet', 'SYSTEM', NULL, '變數', '設定變數', '設定流程變數值', '/static/modules/form_workflow/icons/workflow/opset.svg', 'modules.form_workflow.services.node_handlers.opset_handler.OpSetHandler', '{"variables": "array"}'::jsonb, 'roundrectangle', '#3B82F6', 120, 60, 1, 1, 60, 3600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('4a437deb11b740c1fce996dd329c266a', 'OsExecutor', 'SYSTEM', NULL, '系統', 'OS 命令', '在平台主機執行命令，需系統管理員在 .env 啟用，並由主機管理員授權企業使用本節點。', '/static/modules/form_workflow/icons/workflow/osexecutor.svg', 'modules.form_workflow.services.node_handlers.os_executor_handler.OsExecutorHandler', '{"cwd": "string", "command": "string", "extra_env": "object", "notify_to": "array", "result_var": "string", "stop_after": "boolean", "expect_json": "boolean", "cancel_scope": "string", "expect_pattern": "string", "kill_on_timeout": "string", "timeout_seconds": "integer", "wait_for_result": "boolean", "expect_exit_codes": "array", "notify_on_exception": "boolean"}'::jsonb, 'roundrectangle', '#B45309', 130, 60, -1, -1, 60, 3600, FALSE, TRUE, FALSE, TRUE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('3975c998e7b21e95974a5696c8116dec', 'OsFileRead', 'SYSTEM', NULL, '系統', 'OS 檔案讀取', '唯讀、不經 shell、鎖在允許目錄內；需在 .env 啟用，並由主機管理員授權企業使用本節點與設定允許目錄。', '/static/modules/form_workflow/icons/workflow/osfileread.svg', 'modules.form_workflow.services.node_handlers.os_file_read_handler.OsFileReadHandler', '{"mode": "string", "after": "integer", "lines": "integer", "before": "integer", "keyword": "string", "base_dir": "string", "encoding": "string", "file_path": "string", "match_mode": "string", "occurrence": "string", "result_var": "string", "stop_after": "boolean", "match_scope": "string", "max_scan_ms": "integer", "max_windows": "integer", "max_scan_bytes": "integer"}'::jsonb, 'roundrectangle', '#0F766E', 130, 60, -1, -1, 60, 600, FALSE, TRUE, FALSE, TRUE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('c69bd59a1e96503e575b40f3427456da', 'OsFileWrite', 'SYSTEM', NULL, '系統', 'OS 檔案寫入', '對允許目錄下的檔案追加字串；會先清掉檔尾既有換行再依勾選補換行。需在 .env 啟用並授權企業。', '/static/modules/form_workflow/icons/workflow/osfilewrite.svg', 'modules.form_workflow.services.node_handlers.os_file_write_handler.OsFileWriteHandler', '{"content": "string", "base_dir": "string", "encoding": "string", "file_path": "string", "result_var": "string", "stop_after": "boolean", "newline_after": "boolean", "newline_smart": "boolean", "max_file_bytes": "integer", "newline_before": "boolean", "lock_timeout_ms": "integer", "create_if_missing": "boolean"}'::jsonb, 'roundrectangle', '#B45309', 130, 60, -1, -1, 60, 600, FALSE, TRUE, FALSE, TRUE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('Z/UExTH4w0IaOzgzDxWW+A==', 'ParallelJoin', 'SYSTEM', NULL, '控制', '並行匯合', '等待所有並行分支完成', '/static/modules/form_workflow/icons/workflow/paralleljoin.svg', 'modules.form_workflow.services.node_handlers.paralleljoin_handler.ParallelJoinHandler', '{"mode": "string"}'::jsonb, 'diamond', '#6366F1', 100, 100, -1, 1, 3600, 3600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('w/e2M6xyqAhvEvkQgWd8BQ==', 'SqlExecutor', 'SYSTEM', NULL, '整合', 'SQL 執行', '呼叫平台白名單內的預存程序（唯讀），結果寫入流程變數，可選擇插入一筆簽核註記。企業識別碼由系統強制帶入。', '/static/modules/form_workflow/icons/workflow/sqlexecutor.svg', 'modules.form_workflow.services.node_handlers.sqlexecutor_handler.SqlExecutorHandler', '{"params": "object", "on_error": "string", "result_var": "string", "note_template": "string", "procedure_code": "string", "timeout_seconds": "integer", "write_approval_note": "boolean"}'::jsonb, 'roundrectangle', '#DC2626', 120, 60, 1, 1, 300, 3600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('sF58lG2PXuCvhpKZgO15SA==', 'Start', 'SYSTEM', NULL, '基本', '開始', '流程的起點', '/static/modules/form_workflow/icons/workflow/start.svg', 'modules.form_workflow.services.node_handlers.start_handler.StartHandler', '{}'::jsonb, 'ellipse', '#22C55E', 80, 80, 0, 1, 30, 3600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('qSvMK0N0qXPof/suhUmblA==', 'SubFlow', 'SYSTEM', NULL, '控制', '子流程', '呼叫其他工作流程', '/static/modules/form_workflow/icons/workflow/subflow.svg', 'modules.form_workflow.services.node_handlers.subflow_handler.SubFlowHandler', '{"childFlowId": "string"}'::jsonb, 'roundrectangle', '#0EA5E9', 120, 60, 1, 1, 3600, 3600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('VGKEyCCX5t7BkTY+UFlOaQ==', 'SubSystemProvision', 'SYSTEM', NULL, '整合', '子系統配置', '建立、停用或刪除子系統（含選單、開發者權限）', '/static/modules/form_workflow/icons/workflow/subsystemprovision.svg', 'modules.form_workflow.services.node_handlers.sub_system_provision_handler.SubSystemProvisionHandler', '{"type": "object", "required": ["action"], "properties": {"action": {"enum": ["create", "suspend", "delete"], "type": "string", "description": "動作類型"}, "sub_system_code": {"type": "string", "description": "目標子系統 code（suspend/delete 用，支援變數替換）"}, "sub_system_icon": {"type": "string", "description": "圖示 class（optional，如 bi-box-seam）"}, "sub_system_name": {"type": "string", "description": "子系統名稱（支援變數替換，如 ${f.sub_system_name}）"}, "sub_system_developer": {"type": "string", "description": "開發者 user secure_code（支援變數替換，如 ${f.sub_system_developer}）"}}}'::jsonb, 'roundrectangle', '#8B5CF6', 180, 50, 10, 10, 300, 600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('GS42gCGYslocoBWw5hoB2w==', 'SysEmailRelay', 'SYSTEM', NULL, '系統', '系統 Email 轉發', '透過外部系統發送 Email', '/static/modules/form_workflow/icons/workflow/sysemailrelay.svg', 'modules.form_workflow.services.node_handlers.sys_emailrelay_handler.SysEmailRelayHandler', '{"to": "string", "body": "string", "subject": "string"}'::jsonb, 'roundrectangle', '#EA580C', 120, 60, 1, 1, 300, 3600, FALSE, TRUE, FALSE, TRUE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('AJ231/72iexdExBI3ny4Cg==', 'SysTelegram', 'SYSTEM', NULL, '系統', '系統 Telegram', '系統級 Telegram 通知', '/static/modules/form_workflow/icons/workflow/systelegram.svg', 'modules.form_workflow.services.node_handlers.telegram_handler.TelegramHandler', '{"message": "string"}'::jsonb, 'roundrectangle', '#7C3AED', 120, 60, 1, 1, 120, 3600, FALSE, TRUE, FALSE, TRUE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

INSERT INTO workflow_node_definitions (secure_code, node_type, scope, org_secure_code, category, display_name, description, icon, execution_handler, config_schema, canvas_shape, canvas_color, canvas_width, canvas_height, max_input_connections, max_output_connections, default_timeout_seconds, max_timeout_seconds, require_system_admin, is_active, is_deleted, org_restricted, created_at, updated_at)
VALUES ('ek/jFwZBi84V1Tybz7E/jw==', 'Telegram', 'SYSTEM', NULL, '通知', 'Telegram 通知', '發送 Telegram 訊息', '/static/modules/form_workflow/icons/workflow/telegram.svg', 'modules.form_workflow.services.node_handlers.telegram_handler.TelegramHandler', '{"chat_id": "string", "message": "string"}'::jsonb, 'roundrectangle', '#0088CC', 120, 60, 1, 1, 120, 3600, FALSE, TRUE, FALSE, FALSE, now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC')
ON CONFLICT (node_type) DO NOTHING;

COMMIT;
