-- BeakPlatform Menu Factory Defaults (install-only)
-- Generated: 2026-04-01 09:22 UTC
-- 
-- 安全機制: 只在 menu_defaults 表為空時才插入
-- (upgrade 不會覆蓋用戶已儲存的預設值)

-- 條件: 僅當 menu_defaults 表為空時執行
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM menu_defaults LIMIT 1) THEN

        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('dashboard', '儀表板', '{}'::jsonb, NULL, 'route', 'main.dashboard', 0, 0, NULL, false, true, NULL, '["EMPLOYEE", "EXTERNAL", "ORG_ADMIN", "SYSTEM_ADMIN"]'::jsonb, '["EMPLOYEE", "EXTERNAL_USERS", "ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('personal_settings', '個人設定', '{}'::jsonb, NULL, 'route', 'main.personal_settings', 1, 0, NULL, false, true, NULL, '["EMPLOYEE", "EXTERNAL", "ORG_ADMIN", "SYSTEM_ADMIN"]'::jsonb, '["EMPLOYEE", "EXTERNAL_USERS", "ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('form_workflow.center', '表單中心', '{}'::jsonb, NULL, 'route', 'form_workflow_web.center', 2, 0, NULL, false, true, NULL, '["EMPLOYEE", "EXTERNAL", "ORG_ADMIN", "SYSTEM_ADMIN"]'::jsonb, '["EMPLOYEE", "ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('form_workflow', '表單流程', '{}'::jsonb, 'ri-flow-chart', 'header', NULL, 3, 0, NULL, false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["FLOW_DESIGNER", "FORM_DESIGNER", "ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('spec_formulate', '規格制定模組', '{"en": "Spec Formulate"}'::jsonb, 'ri-file-list-line', 'header', NULL, 4, 0, NULL, false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN", "SPEC_DESIGNER"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('nocode_builder', '子系統開發模組', '{"en": "NoCode Builder"}'::jsonb, 'ri-database-2-line', 'header', NULL, 5, 0, NULL, false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN", "SUBSYS_DESIGNER"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('security_localsystem', '本機安全', '{}'::jsonb, NULL, 'header', NULL, 6, 0, NULL, false, false, NULL, '["SYSTEM_ADMIN"]'::jsonb, '[]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('org_management', '企業管理', '{}'::jsonb, NULL, 'header', NULL, 7, 0, NULL, true, false, NULL, '["SYSTEM_ADMIN"]'::jsonb, '[]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('server_settings', '主機設定', '{}'::jsonb, NULL, 'route', 'hostconfig.server_settings', 8, 0, NULL, false, false, NULL, '["SYSTEM_ADMIN"]'::jsonb, '[]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('perm_mgmt', '權限管理', '{}'::jsonb, NULL, 'header', NULL, 10, 0, NULL, true, false, NULL, '["SYSTEM_ADMIN"]'::jsonb, '[]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('org_config_mgr', '系統管理', '{}'::jsonb, NULL, 'header', NULL, 12, 0, NULL, true, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('org_account', '帳號管理', '{}'::jsonb, NULL, 'header', NULL, 13, 0, NULL, false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('jobs_config', '職級職稱', '{}'::jsonb, NULL, 'header', NULL, 14, 0, NULL, false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('departments', '部門設定', '{}'::jsonb, NULL, 'route', 'departments.department_settings', 15, 0, NULL, false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('groups', '社群設定', '{}'::jsonb, NULL, 'route', 'groups.group_settings', 16, 0, NULL, false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('org_security', '系統安全', '{}'::jsonb, NULL, 'header', NULL, 18, 0, NULL, false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('platform_help', '說明', '{}'::jsonb, NULL, 'header', NULL, 19, 0, NULL, false, true, NULL, '["EMPLOYEE", "EXTERNAL", "ORG_ADMIN", "SYSTEM_ADMIN"]'::jsonb, '["EMPLOYEE", "EXTERNAL_USERS", "ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('spec_formulate.spec_multifaceted', '規格管理', '{}'::jsonb, NULL, 'route', 'spec_formulate_web.spec_multifaceted', 0, 1, 'spec_formulate', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN", "SPEC_DESIGNER"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('redis_monitor', 'Redis監看', '{}'::jsonb, 'ri-database-2-line', 'url', '/server-manage/redis-monitor', 0, 1, NULL, false, false, NULL, '["SYSTEM_ADMIN"]'::jsonb, '[]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('job_matrix', '職級職稱矩陣', '{}'::jsonb, NULL, 'route', 'job_levels.job_matrix', 0, 1, 'jobs_config', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('numbering', '編號設定', '{}'::jsonb, NULL, 'route', 'numbering.list_rules', 0, 1, 'org_account', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('menu_manage', '選單管理', '{}'::jsonb, NULL, 'route', 'menu.list_menu', 0, 1, 'perm_mgmt', false, false, NULL, '["SYSTEM_ADMIN"]'::jsonb, '[]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('organizations_contracts', '企業與合約管理', '{}'::jsonb, NULL, 'route', 'organizations.list_orgs', 0, 1, 'org_management', false, false, NULL, '["SYSTEM_ADMIN"]'::jsonb, '[]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('login_fail_monitor', '登入錯誤監看', '{}'::jsonb, NULL, 'url', '/security/login-failures/', 0, 1, 'security_localsystem', false, false, NULL, '["SYSTEM_ADMIN"]'::jsonb, '[]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('login_fail_monitor_org', '登入錯誤監看', '{}'::jsonb, NULL, 'url', '/security/login-failures/', 0, 1, 'org_security', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('module_perm_mgmt', '模組權限管理', '{}'::jsonb, NULL, 'route', 'admin.module_permissions', 0, 1, NULL, false, false, 'module:manage', '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('system_settings', '系統設定', '{}'::jsonb, NULL, 'route', 'admin.settings', 0, 1, 'org_config_mgr', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('form_workflow.workflows', '流程設計', '{}'::jsonb, NULL, 'route', 'form_workflow_web.workflows', 0, 1, 'form_workflow', false, false, 'form_workflow.workflow.manage', '["ORG_ADMIN"]'::jsonb, '["FLOW_DESIGNER", "ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('platform_help.system_admin', '系統管理員說明', '{}'::jsonb, NULL, 'route', 'platform_help.index', 0, 1, 'platform_help', false, false, NULL, '["SYSTEM_ADMIN"]'::jsonb, '[]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('nocode_builder.sub_systems', '子系統開發', '{"en": "Sub System Development"}'::jsonb, NULL, 'route', 'nocode_builder_web.sub_system_list', 0, 1, 'nocode_builder', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN", "SUBSYS_DESIGNER"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('org_rate_limits', '速率限制', '{}'::jsonb, NULL, 'url', '/security/rate-limits/', 1, 1, 'org_security', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('form_workflow.templates', '表單範本', '{}'::jsonb, NULL, 'route', 'form_workflow_web.templates', 1, 1, 'form_workflow', false, false, 'form_workflow.template.manage', '["ORG_ADMIN"]'::jsonb, '["FORM_DESIGNER", "ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('permission_central_org', '權限中央管理', '{}'::jsonb, NULL, 'url', '/permissions/', 1, 1, NULL, false, false, NULL, '["ORG_ADMIN"]'::jsonb, '[]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('data_maintenance', '資料維護', '{}'::jsonb, NULL, 'route', 'hostconfig.data_maintenance', 1, 1, NULL, false, false, NULL, '["SYSTEM_ADMIN"]'::jsonb, '[]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('platform_help.org_admin', '企業管理員說明', '{}'::jsonb, NULL, 'route', 'platform_help.index', 1, 1, 'platform_help', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('job_levels', '職等設定', '{}'::jsonb, NULL, 'route', 'job_levels.list_job_levels', 1, 1, 'jobs_config', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('nocode_builder.lookup', '選項-清單-資料樹', '{"en": "Lookup List"}'::jsonb, NULL, 'route', 'nocode_builder_web.lookup_manager', 1, 1, 'nocode_builder', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN", "SUBSYS_DESIGNER"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('org_databases_system', '企業獨立資料庫管理', '{}'::jsonb, NULL, 'route', 'org_databases.system_view', 1, 1, 'org_management', false, false, NULL, '["SYSTEM_ADMIN"]'::jsonb, '[]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('org_admins', '企業管理員', '{}'::jsonb, NULL, 'route', 'org_admins.list_admins', 1, 1, 'org_config_mgr', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('sys_accounts', '系統管理員帳號', '{}'::jsonb, NULL, 'route', 'sys_accounts.list_accounts', 1, 1, 'perm_mgmt', false, false, NULL, '["SYSTEM_ADMIN"]'::jsonb, '[]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('roles', '角色管理', '{}'::jsonb, NULL, 'route', 'roles.list_roles', 1, 1, 'org_account', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('permission_central', '權限中央管理', '{}'::jsonb, NULL, 'url', '/permissions/', 2, 1, 'perm_mgmt', false, false, NULL, '["SYSTEM_ADMIN"]'::jsonb, '[]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('org_databases_org', '獨立資料庫', '{}'::jsonb, NULL, 'route', 'org_databases.org_view', 2, 1, 'org_config_mgr', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('platform_help.employee', '企業成員說明', '{}'::jsonb, NULL, 'route', 'platform_help.index', 2, 1, 'platform_help', false, false, NULL, '["EMPLOYEE"]'::jsonb, '["EMPLOYEE"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('account_roles', '帳號角色權限表', '{"en": "Account Roles", "ja": "アカウント役割一覧", "zh-CN": "账号角色权限表"}'::jsonb, NULL, 'route', 'account_roles.index', 2, 1, NULL, false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('job_families', '職系設定', '{}'::jsonb, NULL, 'route', 'job_families.list_job_families', 2, 1, 'jobs_config', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('alert_broadcasts_org', '緊急廣播記錄', '{}'::jsonb, NULL, 'url', '/security/alert-broadcasts/', 2, 1, 'org_security', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('form_workflow.mappings', '配對管理', '{}'::jsonb, NULL, 'route', 'form_workflow_web.mappings', 2, 1, 'form_workflow', false, false, 'form_workflow.workflow.manage', '["ORG_ADMIN"]'::jsonb, '["FLOW_DESIGNER", "FORM_DESIGNER", "ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('nocode_builder.views', '視圖管理', '{"en": "View Manager"}'::jsonb, NULL, 'route', 'nocode_builder_web.index', 2, 1, 'nocode_builder', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN", "SUBSYS_DESIGNER"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('users', '企業成員帳號', '{}'::jsonb, NULL, 'route', 'users.list_users', 2, 1, 'org_account', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('job_titles', '職稱設定', '{}'::jsonb, NULL, 'route', 'job_titles.list_job_titles', 3, 1, 'jobs_config', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('work_schedules', '基本班表', '{}'::jsonb, NULL, 'route', 'work_schedules.list_schedules', 3, 1, 'org_account', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('form_workflow.categories', '分類管理', '{}'::jsonb, NULL, 'route', 'form_workflow_web.categories', 3, 1, 'form_workflow', false, false, 'form_workflow.admin', '["ORG_ADMIN"]'::jsonb, '["FLOW_DESIGNER", "FORM_DESIGNER", "ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('nocode_builder.lab', '頁面管理', '{"en": "Page Manager"}'::jsonb, NULL, 'route', 'nocode_builder_web.lab', 3, 1, 'nocode_builder', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN", "SUBSYS_DESIGNER"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('modules', '模組管理', '{}'::jsonb, NULL, 'route', 'modules.list_modules', 3, 1, 'perm_mgmt', false, false, NULL, '["SYSTEM_ADMIN"]'::jsonb, '[]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('platform_help.external', '外部廠商說明', '{}'::jsonb, NULL, 'route', 'platform_help.index', 3, 1, 'platform_help', false, false, NULL, '["EXTERNAL"]'::jsonb, '["EXTERNAL_USERS"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('cg_databases_overview', '集團資料庫總覽', '{}'::jsonb, NULL, 'route', 'cg_databases.overview', 3, 1, 'org_management', false, false, NULL, '["SYSTEM_ADMIN"]'::jsonb, '[]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('external_users', '外部廠商', '{}'::jsonb, NULL, 'route', 'external_users.list_external_users', 4, 1, 'org_account', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('form_workflow.form_themes', '表單風格管理', '{}'::jsonb, NULL, 'route', 'form_workflow_web.form_themes', 4, 1, 'form_workflow', false, false, 'form_workflow.admin', '["ORG_ADMIN"]'::jsonb, '["FLOW_DESIGNER", "FORM_DESIGNER", "ORG_ADMIN"]'::jsonb, 'factory_install', NOW());
        INSERT INTO menu_defaults (code, title, title_i18n, icon, link_type, link_target, display_order, depth, parent_code, is_expanded, is_shared, required_permission, user_types, role_codes, saved_by, saved_at) VALUES ('job_approval_categories', '核決權限', '{}'::jsonb, NULL, 'route', 'approval_categories.list_categories', 4, 1, 'jobs_config', false, false, NULL, '["ORG_ADMIN"]'::jsonb, '["ORG_ADMIN"]'::jsonb, 'factory_install', NOW());

    END IF;
END $$;