"""CrowdSec enforcer — writes and removes od-bridge decisions via LAPI.

Block actions create an alert with an embedded ban decision through
`/v1/alerts`. Unblock actions delete decisions through `/v1/decisions`,
filtered by `scopes`, `value`, and `scenario=od-bridge`.

Machine credentials are generated by the installer at
`/state/crowdsec_machine.json`; if the file is missing, the enforcer
returns `no_machine_creds`.
"""
from datetime import datetime, timezone
import json
import logging
import time
from pathlib import Path

import aiohttp

log = logging.getLogger("enforce.crowdsec")
STATE = Path("/state/crowdsec_machine.json")
# LAPI rejects a machine login whose User-Agent is not exactly "name/version"
# (it answers 401 "incorrect Username or Password"); aiohttp's default has two slashes.
USER_AGENT = "od-bridge/1.0"

_token: str | None = None
_token_expires_at: float = 0.0


async def _login(session: aiohttp.ClientSession, base: str) -> str | None:
    if not STATE.exists():
        log.warning("crowdsec machine creds missing at %s — enforcer skipped", STATE)
        return None
    creds = json.loads(STATE.read_text())
    async with session.post(f"{base}/v1/watchers/login", json={
        "machine_id": creds["machine_id"], "password": creds["password"],
    }, timeout=aiohttp.ClientTimeout(total=10)) as r:
        if r.status != 200:
            log.warning("crowdsec login %s: %s", r.status, await r.text())
            return None
        j = await r.json()
        return j.get("token")


async def _token_get(session: aiohttp.ClientSession, base: str) -> str | None:
    global _token, _token_expires_at
    now = time.time()
    if _token and now < _token_expires_at - 60:
        return _token
    t = await _login(session, base)
    if t:
        _token = t
        _token_expires_at = now + 60 * 60   # CrowdSec default
    return t


_SCOPE_MAP = {"ip": "Ip", "cidr": "Range", "country": "Country", "asn": "AS"}
_SOURCE_FIELD_MAP = {"Ip": "ip", "Range": "range", "Country": "cn", "AS": "as_number"}


def _clear_token() -> None:
    global _token, _token_expires_at
    _token = None
    _token_expires_at = 0.0


async def _lapi_request(
    session: aiohttp.ClientSession,
    base: str,
    method: str,
    path: str,
    **kwargs,
) -> tuple[int, str] | None:
    token = await _token_get(session, base)
    if not token:
        return None

    async def send(current_token: str) -> tuple[int, str]:
        async with session.request(
            method,
            f"{base}{path}",
            headers={"Authorization": f"Bearer {current_token}"},
            timeout=aiohttp.ClientTimeout(total=10),
            **kwargs,
        ) as r:
            return r.status, await r.text()

    status, body = await send(token)
    if status != 401:
        return status, body

    _clear_token()
    token = await _token_get(session, base)
    if not token:
        return status, body
    return await send(token)


async def apply(decision: dict, cfg) -> dict:
    action = decision.get("action")
    target_type = decision.get("target_type")
    target = decision.get("target_value")
    ttl = decision.get("ttl_seconds")
    reason = (decision.get("reason") or "od-bridge")[:200]

    scope = _SCOPE_MAP.get(target_type)
    if not scope:
        return {"ok": False, "error": f"unsupported_target_type:{target_type}"}
    if not target:
        return {"ok": False, "error": "empty_target"}

    base = cfg.crowdsec_lapi_url.rstrip("/")

    async with aiohttp.ClientSession(headers={"User-Agent": USER_AGENT}) as s:
        if action == "block":
            duration = f"{ttl}s" if ttl else "8760h"
            now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
            source = {"scope": scope, "value": target, _SOURCE_FIELD_MAP[scope]: target}
            payload = [{
                "capacity": 0,
                "decisions": [{
                    "duration": duration,
                    "origin": "od-bridge",
                    "scenario": "od-bridge",
                    "scope": scope,
                    "type": "ban",
                    "value": target,
                }],
                "events": [],
                "events_count": 1,
                "leakspeed": "0",
                "message": reason,
                "scenario": "od-bridge",
                "scenario_hash": "",
                "scenario_version": "",
                "simulated": False,
                "source": source,
                "start_at": now,
                "stop_at": now,
            }]
            result = await _lapi_request(s, base, "POST", "/v1/alerts", json=payload)
            if result is None:
                return {"ok": False, "error": "no_machine_creds"}
            status, body = result
            return {"ok": status in (200, 201), "status": status, "body": body[:300]}

        if action == "unblock":
            result = await _lapi_request(
                s,
                base,
                "DELETE",
                "/v1/decisions",
                params={"scopes": scope, "value": target, "scenario": "od-bridge"},
            )
            if result is None:
                return {"ok": False, "error": "no_machine_creds"}
            status, body = result
            return {"ok": status == 200, "status": status, "body": body[:300]}

        return {"ok": False, "error": f"unsupported_action:{action}"}
